-- Part 3 - Joins

-- 1. FIND OUT COUNTRY NAME AND REGION NAME FROM COUNTRIES AND REGION TABLE
   SELECT * FROM COUNTRIES;
   SELECT * FROM REGIONS;

SELECT COUNTRY_NAME, REGION_NAME
    FROM COUNTRIES INNER JOIN REGIONS
ON COUNTRIES.REGION_ID = REGIONS.REGION_ID;

-- 2. FIND OUT FIRST_NAME AND JOB_TITLE FROM JOBS AND EMPLOYEES TABLE
    SELECT FIRST_NAME, JOB_TITLE
    FROM JOBS J INNER JOIN EMPLOYEES
    ON J.JOB_ID = EMPLOYEES.JOB_ID;

-- 3. FIND OUT DEPARTMENT_NAME AND CITY
    SELECT DEPARTMENT_NAME, CITY
    FROM DEPARTMENTS D INNER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID;

-- 4. FIND OUT ALL CITIES  AND COUNTRY NAMES
    SELECT CITY,COUNTRY_NAME
    FROM LOCATIONS L JOIN COUNTRIES C
    ON L.COUNTRY_ID=C.COUNTRY_ID;


-- 5. FIND OUT FIRST_NAME, LAST NAME, DEPARTMENT ID , DEPARTMENT NAME  FOR DEPARTMENT ID 80 OR 40
    SELECT FIRST_NAME, LAST_NAME, D.DEPARTMENT_ID
    FROM DEPARTMENTS D JOIN EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
    WHERE D.DEPARTMENT_ID IN (80,40);

-- 6. FIND OUT CITY , COUNTRY_NAME OF THAT CITY , REGION_NAME OF THAT CITY
    SELECT CITY, COUNTRY_NAME, REGION_NAME
    FROM COUNTRIES C JOIN LOCATIONS L
    ON L.COUNTRY_ID=C.COUNTRY_ID
    JOIN REGIONS R
    ON R.REGION_ID=C.REGION_ID;


-- 7. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY
    SELECT E.FIRST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME, L.CITY FROM EMPLOYEES E
    JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID
    JOIN DEPARTMENTS D
    ON  E.DEPARTMENT_ID=D.DEPARTMENT_ID
    JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID;


-- 8. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY , COUNTRY_NAME , REGION_NAME

    SELECT FIRST_NAME, JOB_TITLE, DEPARTMENT_NAME, CITY, COUNTRY_NAME, REGION_NAME FROM EMPLOYEES E
    JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID
    JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
    JOIN COUNTRIES C
    ON L.COUNTRY_ID = C.COUNTRY_ID
    JOIN REGIONS R
    ON C.REGION_ID = R.REGION_ID;


--9. FIND OUR  EMPLOYEES FIRST_NAME, LAST NAME, DEPARTMENT ID AND ALL DEPARTMENTS
--  INCLUDING  WHERE DO NOT HAVE ANY EMPLOYEE
--  (MATCHES ONE AND ALL INFORMATION FROM RIGHT TABLE)
    SELECT FIRST_NAME, LAST_NAME, E.DEPARTMENT_ID, DEPARTMENT_NAME
    FROM EMPLOYEES E  RIGHT OUTER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;


--10. FIND OUT ALL DEPARTMENT_NAME  , LOCATION_ID , AND COUNTRY_ID
-- INCLUDING THOSE LOCATIONS  WITH NO DEPARTMENT
    SELECT DEPARTMENT_NAME, L.LOCATION_ID, COUNTRY_ID
    FROM DEPARTMENTS D RIGHT OUTER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID;


--11.FIND OUT DEPARTMENT_NAME , LOCATION_ID , AND COUNTRY_NAME
-- INCLUDING THOSE COUNTRIES WITH NO DEPARTMENT

    SELECT DEPARTMENT_NAME, L.LOCATION_ID, COUNTRY_NAME FROM DEPARTMENTS D
    RIGHT OUTER JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
     RIGHT JOIN COUNTRIES C
    ON L.COUNTRY_ID = C.COUNTRY_ID;



--12. FIND OUT EMPLOYEES FIRST_NAME, DEPARTMENT ID AND DEPARTMENT NAME
-- INCLUDING THOSE DOES NOT HAVE DEPARTMENT
-- INCLUDING THOSE DEPARTMENTS  DOES NOT HAVE ANY MATCHING EMPLOYEES

SELECT FIRST_NAME, E.DEPARTMENT_ID, DEPARTMENT_NAME FROM EMPLOYEES E
FULL JOIN  DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

