SELECT * FROM JOBS;

-- get me how many different departments we have for 'each' location_id
SELECT * FROM DEPARTMENTS;
SELECT COUNT (*) FROM DEPARTMENTS;

SELECT LOCATION_ID FROM DEPARTMENTS;
SELECT COUNT (LOCATION_ID) FROM DEPARTMENTS;

-- Shows the UNIQUE LOCATION_ID
SELECT DISTINCT LOCATION_ID FROM DEPARTMENTS; -- 7 UNIQUE LOCATION_ID

-- Shows the UNIQUE LOCATION_ID
SELECT LOCATION_ID FROM DEPARTMENTS
GROUP BY LOCATION_ID;


SELECT LOCATION_ID, COUNT(*) FROM DEPARTMENTS
GROUP BY LOCATION_ID;


-- get me how many locations we have for each country_id
SELECT * FROM LOCATIONS;

SELECT COUNTRY_ID, COUNT(*) FROM LOCATIONS
GROUP BY COUNTRY_ID
ORDER BY COUNTRY_ID;


-- get me how many countries we have for each region_ID (countries)
SELECT REGION_ID, COUNT(*) FROM COUNTRIES
GROUP BY REGION_ID
ORDER BY COUNT(*) DESC;


-- AS -- aliasys
SELECT REGION_ID, COUNT(*) AS TOTAL_NUM_FOR_EACH_RI FROM COUNTRIES
GROUP BY REGION_ID
ORDER BY COUNT(*) DESC;

-- AS -- aliasys
SELECT REGION_ID, COUNT(*) AS "TOTAL NUM FOR EACH RI" FROM COUNTRIES
GROUP BY REGION_ID
ORDER BY "TOTAL NUM FOR EACH RI";











