/*
    VIEW
        - Virtual table.
 */
SELECT * FROM EMPLOYEES;


SELECT SUBSTR(FIRST_NAME, 0, 1) ||  SUBSTR(LAST_NAME, 0, 1) as INITIALS,  FIRST_NAME || ' makes $' || SALARY  as EMPLOYEE_SALARY FROM EMPLOYEES;

CREATE VIEW SDET
AS SELECT SUBSTR(FIRST_NAME, 0, 1) ||  SUBSTR(LAST_NAME, 0, 1) as INITIALS,  FIRST_NAME || ' makes $' || SALARY  as EMPLOYEE_SALARY
   FROM EMPLOYEES;

SELECT * FROM SDET;
SELECT INITIALS FROM SDET;
SELECT EMPLOYEE_SALARY FROM SDET;


-- How can I remove this view
DROP VIEW SDET;