SELECT * FROM EMPLOYEES;


SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MANAGER_ID
FROM EMPLOYEES;



-- I want to get employees info  with their managers info
SELECT  *
FROM EMPLOYEES E1 INNER JOIN EMPLOYEES E2
                             ON E1.EMPLOYEE_ID = E2.MANAGER_ID;




SELECT E2.EMPLOYEE_ID, E2.FIRST_NAME, E2.LAST_NAME, E2.MANAGER_ID, E1.FIRST_NAME, E1.LAST_NAME
FROM EMPLOYEES E1 INNER JOIN EMPLOYEES E2
ON E1.EMPLOYEE_ID = E2.MANAGER_ID;